apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - git@github.com:talos-systems/metal-metadata-server/config/default?ref=master
images:
  - name: server
    newName: docker.io/autonomy/metal-metadata-server
    newTag: 1557ee4
