apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - git@github.com:talos-systems/metal-controller-manager/config/default?ref=master
images:
  - name: controller
    newName: docker.io/autonomy/metal-controller-manager
    newTag: db197c7
